### PR TITLE
fix: detailed exit code command options misspelled

### PR DESCRIPTION
**Pull request by cmcnicholas**
See https://developer.hashicorp.com/terraform/cli/commands/plan#detailed-exitcode for correct spelling.

### CODE REVIEW

**Review by b4nst — APPROVED** [review]

**Comment by b4nst** [comment]
Nice spot, thanks!

**Comment by cmcnicholas** [comment]
Thanks for the effort on this, plugin really helped me cleanup our solution 👍

**Comment by b4nst** [comment]
Glad to hear that, this is still work in progress but we hope making terraform mono repos easier to manage!

**Comment by cmcnicholas** [comment]
> Glad to hear that, this is still work in progress but we hope making terraform mono repos easier to manage! We'll push a release later today with your fix included.

Amazing stuff 👍 look forward to this continuing to make my life easier 😂

**Pull request merged**
